In [1]:
import fastai
from fastai.vision import *
from fastai.callbacks import *
from fastai.utils.mem import *

from torchvision.models import vgg16_bn

In [2]:
def gram_matrix(x):
    n,c,h,w = x.size()
    x = x.view(n, c, -1)
    return (x @ x.transpose(1,2))/(c*h*w)

In [36]:
a = torch.rand((2,3,4,4))
a.shape

torch.Size([2, 3, 4, 4])

In [37]:
gram_matrix(a).shape

torch.Size([2, 3, 3])

In [38]:
n,c,h,w = a.size()
print(n,c,h,w)

2 3 4 4


In [39]:
a2 = a.view(n, c, -1)
a2.shape

torch.Size([2, 3, 16])

In [40]:
a2.transpose(1,2).shape

torch.Size([2, 16, 3])

In [41]:
a_res = a2 @ a2.transpose(1,2)
a_res.shape

torch.Size([2, 3, 3])

In [42]:
a_res2 = torch.matmul(a2, a2.transpose(1,2))
a_res2.shape

torch.Size([2, 3, 3])

In [43]:
a_res == a_res2

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])

In [44]:
torch.all(a_res == a_res2)

tensor(True)

In [45]:
a_res3 = a_res.clone()
a_res3[0,0,0] = 1.42
print(a_res)
print(a_res3)

tensor([[[5.4349, 2.6643, 4.0337],
         [2.6643, 2.9286, 3.1438],
         [4.0337, 3.1438, 5.9317]],

        [[6.4938, 4.7621, 3.8013],
         [4.7621, 5.4030, 3.2982],
         [3.8013, 3.2982, 4.3791]]])
tensor([[[1.4200, 2.6643, 4.0337],
         [2.6643, 2.9286, 3.1438],
         [4.0337, 3.1438, 5.9317]],

        [[6.4938, 4.7621, 3.8013],
         [4.7621, 5.4030, 3.2982],
         [3.8013, 3.2982, 4.3791]]])


In [46]:
torch.all(a_res == a_res3)

tensor(False)

In [47]:
torch.any(a_res == a_res3)

tensor(True)